name: 'xcode-build-github-action'
description: ''
inputs:
  export-method:
    description: >
      Define the profile type,
      can be appstore, adhoc, development, enterprise, developer_id, mac_installer_distribution
    required: true
  configuration:
    description: >
      The configuration to use when building the app. Defaults to 'Debug'
    required: false
    default: 'Debug'
  workspace:
    description: 'Path to the workspace file'
    required: false
    default: ''
  project:
    description: 'Path to the project file'
    required: false
    default: ''
  scheme:
    description: >
      The project's scheme. Make sure it's marked as `Shared`.
      Defaults to 'Unity-iPhone'
    required: false
    default: 'Unity-iPhone'
  sdk:
    description: >
      The SDK that should be used for building the application.
      Defaults to 'iphoneos'
    required: false
    default: 'iphoneos'
  include-bitcode:
    description: >
      Should the ipa file include bitcode?
      Defaults to false
    required: false
    default: false
  include-symbols:
    description: >
      Should the ipa file include symbols?
      Defaults to false
    required: false
    default: false
  output-directory:
    description: >
      The directory in which the ipa file should be stored in
    required: true
    default: ''
  team-id:
    description: >
      The ID of your Developer Portal team if you're in multiple teams
    required: true
runs:
  using: 'node16'
  main: 'dist/index.js'
branding:
  icon: "download"
  color: "orange"